config/routes.rb
Mypage::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'pages#index'
  match '/page/:page' => 'pages#index', :as => :page

end

app/views/pages/index.html.erb
<div id="body">
  <%= link_to (image_tag 'settings_lt.png', :class => 'settings flt-rt', :width => '25px'), admin_page_path(@page.id), :target => '_blank' %>

  <div class="pages-container">
    <% @pages.each do |page| %>
        <%= link_to "<div class='page-button clickable #{'active' if @page.id == page.id}'>#{page.name}</div>".html_safe, page_path(page.id) %>
    <% end %>
  </div>

  <div class="top clear">
    <%= get_windows(@page.id, 0) %>
  </div>
  <!--end top col-->

  <% if @page.column_1_count > 0 %>
      <% width = ((@page.column_1_count.to_f / 6) * 100) %>
      <div class="flt-lft center width-<%= @page.column_1_count %>-sixth" style="width:<%= width %>%">
        <%= get_windows(@page.id, 1) %>
      </div>
      <!--end col 1 -->
  <% end %>

  <% if @page.column_2_count > 0 %>
      <% width = ((@page.column_2_count.to_f / 6) * 100) %>
      <div class="flt-lft center width-<%= @page.column_2_count %>-sixth" style="width:<%= width %>%">
        <%= get_windows(@page.id, 2) %>
      </div>
      <!--end col 2 -->
  <% end %>

  <% if @page.column_3_count > 0 %>
      <% width = ((@page.column_3_count.to_f / 6) * 100) %>
      <div class="flt-lft center width-<%= @page.column_3_count %>-sixth" style="width:<%= width %>%">
        <%= get_windows(@page.id, 3) %>
      </div>
      <!--end col 3 -->
  <% end %>

  <% if @page.column_4_count > 0 %>
      <% width = ((@page.column_4_count.to_f / 6) * 100) %>
      <div class="flt-lft center width-<%= @page.column_4_count %>-sixth" style="width:<%= width %>%">
        <%= get_windows(@page.id, 4) %>
      </div>
      <!--end col 4 -->
  <% end %>

  <% if @page.column_5_count > 0 %>
      <% width = ((@page.column_5_count.to_f / 6) * 100) %>
      <div class="flt-lft center width-<%= @page.column_5_count %>-sixth" style="width:<%= width %>%">
        <%= get_windows(@page.id, 5) %>
      </div>
      <!--end col 5 -->
  <% end %>

  <% if @page.column_6_count > 0 %>
      <% width = ((@page.column_6_count.to_f / 6) * 100) %>
      <div class="flt-lft center width-<%= @page.column_6_count %>-sixth" style="width:<%= width %>%">
        <%= get_windows(@page.id, 6) %>
      </div>
      <!--end col 6 -->
  <% end %>



  <br class="clear"/>

  <div class="bottom">
    <%= get_windows(@page.id, -1) %>
  </div>
  <!--end bottom col-->
</div>

app/views/pages/temp.html.erb
'<div class="category button dev"><a style="color: #3F4F26;" class="category_link" href="#">Dev</a>'

'  <div class="dropdown_menu_list_wrapper" style="display: none; ">'
'    <ul class="dropdown_menu_list">'
'      <li class="dev tooltip"><a href="http://localhost:3013/admin" class="batch_action">Admin</a></li>'
'      <li class="dev tooltip"><a href="http://localhost:3013/cms-admin" class="batch_action">CMS</a></li>'
'      <li class="dev "><a href="http://localhost:3013/dean" class="batch_action">Public - Dean</a></li>'
'    </ul>'
'  </div>'

'</div>'